name: Docker

on:
    push:
        branches:
            - "main"
        paths:
            - "linux/**"
            - "windows/**"
            - ".github/workflows/docker.yml"
    workflow_dispatch:
    schedule:
        - cron: "0 0 1 * *"

permissions:
    contents: read

concurrency:
    group: docker-publish
    cancel-in-progress: false

jobs:
    publish:
        uses: Faulo/workflows-docker/.github/workflows/publish.yml@v1
        with:
            image: inbound-agent
            tag: latest
        secrets:
            DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
            DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
